#!/usr/bin/env node
/**
 * build.js — Concatenates source modules into js/app.jsx
 *
 * Usage:  node build.js
 *
 * Source files (edit these):
 *   js/app-core.jsx         — State, hooks, handlers (top section)
 *   js/pages/dashboard.jsx  — Dashboard page
 *   js/pages/schedule.jsx   — Schedule page
 *   js/components/board-components.jsx — Shared board/gallery components
 *   js/pages/board.jsx      — Board page
 *   js/pages/gallery.jsx    — Gallery page
 *   js/pages/budget.jsx     — Budget page
 *   js/pages/guide.jsx      — Guide page
 *   js/pages/newsletter.jsx — Newsletter page
 *   js/pages/admin.jsx      — Admin page
 *   js/app-shell.jsx        — renderContent + main layout + ReactDOM.render
 *
 * Output: js/app.jsx (auto-generated, do not edit directly)
 */

const fs = require('fs');
const path = require('path');

const BASE = __dirname;

const modules = [
  'js/app-core.jsx',
  'js/pages/dashboard.jsx',
  'js/pages/schedule.jsx',
  'js/components/board-components.jsx',
  'js/pages/board.jsx',
  'js/pages/gallery.jsx',
  'js/pages/budget.jsx',
  'js/pages/guide.jsx',
  'js/pages/newsletter.jsx',
  'js/pages/admin.jsx',
  'js/app-shell.jsx',
];

let output = '// ╔══════════════════════════════════════════════════════════════╗\n';
output +=    '// ║  app.jsx — AUTO-GENERATED by build.js                      ║\n';
output +=    '// ║  Do NOT edit this file directly.                            ║\n';
output +=    '// ║  Edit source modules in js/pages/ and js/components/        ║\n';
output +=    '// ║  then run: node build.js                                    ║\n';
output +=    '// ╚══════════════════════════════════════════════════════════════╝\n\n';

let totalLines = 0;

modules.forEach(mod => {
  const filePath = path.join(BASE, mod);
  if (!fs.existsSync(filePath)) {
    console.error(`ERROR: ${mod} not found`);
    process.exit(1);
  }
  const content = fs.readFileSync(filePath, 'utf8');
  const lineCount = content.split('\n').length;
  totalLines += lineCount;

  output += `// ════════════════════════════════════════════════════════════════\n`;
  output += `// 📄 ${mod} (${lineCount} lines)\n`;
  output += `// ════════════════════════════════════════════════════════════════\n\n`;
  output += content + '\n\n';
});

fs.writeFileSync(path.join(BASE, 'js/app.jsx'), output);
console.log(`✅ js/app.jsx built (${totalLines} source lines → ${output.split('\n').length} output lines)`);
console.log('   Modules:');
modules.forEach(m => {
  const c = fs.readFileSync(path.join(BASE, m), 'utf8').split('\n').length;
  console.log(`   ${m.padEnd(42)} ${String(c).padStart(5)} lines`);
});
