"""
Vercel Serverless Function: HWPX Template Fill
POST /api/hwpx-fill — Fill preprocessed HWPX templates with data (F-13)

Request body:
{
    "template": "salary",   // salary | receipt | minutes
    "documents": [
        { "filename": "급여지급명세서_홍길동_2026-06.hwpx",
          "fields": { "r_name": "홍길동", "pay1_date": "2026-06-25", ... } }
    ]
}

Response: 1 document → .hwpx binary / 2+ documents → .zip binary

The server only substitutes placeholders and packages the archive.
Data collection, formatting, and document splitting are done client-side.
Templates live in api/hwpxfill_templates/ (generated by scripts/preprocess_templates.py).
"""
import io
import json
import re
import zipfile
from http.server import BaseHTTPRequestHandler
from pathlib import Path
from urllib.parse import quote

TEMPLATES_DIR = Path(__file__).parent / 'hwpxfill_templates'
ALLOWED_TEMPLATES = {'salary': '급여지급명세서', 'receipt': '영수증빙', 'minutes': '회의진행일지'}

MAX_DOCUMENTS = 100
MAX_BODY_BYTES = 2 * 1024 * 1024

PLACEHOLDER_RE = re.compile(r'\{\{[a-z0-9_]+\}\}')

# Hancom writes archives in this entry order with everything DEFLATED —
# replicate it so the output is structurally identical to a native file.
ENTRY_ORDER = ['version.xml', 'mimetype', 'META-INF/container.xml', 'settings.xml',
               'Contents/section0.xml', 'Contents/header.xml', 'Contents/content.hpf',
               'META-INF/manifest.xml']


def escape_xml(s):
    return (str(s or '')
            .replace('&', '&amp;')
            .replace('<', '&lt;')
            .replace('>', '&gt;')
            .replace('"', '&quot;'))


def sanitize_filename(name, fallback):
    name = re.sub(r'[/\\]|\.\.', '', str(name or '')).strip()
    if not name:
        name = fallback
    if not name.endswith('.hwpx'):
        name += '.hwpx'
    return name


def load_template(template):
    """Read all template files once. Returns (files dict, section xml str)."""
    tdir = TEMPLATES_DIR / template
    section_path = tdir / 'Contents' / 'section0.xml'
    if not section_path.exists():
        raise FileNotFoundError(
            f'템플릿 누락: {template} — scripts/preprocess_templates.py 실행 후 배포 필요')
    files = {}
    for f in sorted(tdir.rglob('*')):
        if f.is_file():
            files[str(f.relative_to(tdir)).replace('\\', '/')] = f.read_bytes()
    return files, files['Contents/section0.xml'].decode('utf-8')


def fill_section(section_xml, fields):
    """Substitute {{key}} placeholders, then blank out any leftovers."""
    for key, value in (fields or {}).items():
        if not re.fullmatch(r'[a-z0-9_]+', str(key)):
            continue
        section_xml = section_xml.replace('{{%s}}' % key, escape_xml(value))
    return PLACEHOLDER_RE.sub('', section_xml)


def package_hwpx(files, filled_section_xml):
    """Zip template files with the filled section0.xml, preserving entry order."""
    buf = io.BytesIO()
    names = [n for n in ENTRY_ORDER if n in files]
    names += [n for n in sorted(files) if n not in ENTRY_ORDER]
    with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
        for name in names:
            data = filled_section_xml.encode('utf-8') if name == 'Contents/section0.xml' else files[name]
            zf.writestr(name, data)
    return buf.getvalue()


class handler(BaseHTTPRequestHandler):
    def _send(self, status, content_type, body, disposition=None):
        self.send_response(status)
        self.send_header('Content-Type', content_type)
        if disposition:
            self.send_header('Content-Disposition', disposition)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.end_headers()
        self.wfile.write(body)

    def _send_error(self, status, message):
        self._send(status, 'application/json',
                   json.dumps({'error': message}, ensure_ascii=False).encode('utf-8'))

    def do_POST(self):
        try:
            content_length = int(self.headers.get('Content-Length', 0))
            if content_length > MAX_BODY_BYTES:
                return self._send_error(400, '요청 크기 초과 (최대 2MB)')
            data = json.loads(self.rfile.read(content_length))

            template = data.get('template')
            if template not in ALLOWED_TEMPLATES:
                return self._send_error(400, f'지원하지 않는 템플릿: {template}')

            documents = data.get('documents')
            if not isinstance(documents, list) or not documents:
                return self._send_error(400, 'documents가 비어 있습니다')
            if len(documents) > MAX_DOCUMENTS:
                return self._send_error(400, f'문서 수 초과 (최대 {MAX_DOCUMENTS}건)')

            files, section_xml = load_template(template)
            label = ALLOWED_TEMPLATES[template]

            results = []
            for i, doc in enumerate(documents):
                filled = fill_section(section_xml, doc.get('fields'))
                fname = sanitize_filename(doc.get('filename'), f'{label}_{i + 1}')
                results.append((fname, package_hwpx(files, filled)))

            if len(results) == 1:
                fname, blob = results[0]
                return self._send(200, 'application/octet-stream', blob,
                                  f"attachment; filename*=UTF-8''{quote(fname)}")

            buf = io.BytesIO()
            with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as zf:
                seen = set()
                for fname, blob in results:
                    base = fname
                    n = 2
                    while fname in seen:
                        fname = base[:-5] + f'({n}).hwpx'
                        n += 1
                    seen.add(fname)
                    zf.writestr(fname, blob)
            return self._send(200, 'application/zip', buf.getvalue(),
                              f"attachment; filename*=UTF-8''{quote(label + '_일괄.zip')}")

        except FileNotFoundError as e:
            self._send_error(500, str(e))
        except json.JSONDecodeError:
            self._send_error(400, '잘못된 JSON 요청')
        except Exception as e:
            self._send_error(500, str(e))

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()
